### ISSUE TITLE
variable name typo

### ISSUE THREAD

**Issue by ogre** [MaJerle/gps-nmea-parser#12]
Thanks for making this parser !

https://github.com/MaJerle/gps-nmea-parser/blob/develop/gps_nmea_parser/src/include/gps/gps.h#L186
`gps_float_t coarse;                         /*!< Ground coarse */`
should be
`gps_float_t course;                         /*!< Ground course */`

**Comment by MaJerle** [comment]
You are right. Fixed on develop branch.
