### ISSUE TITLE
Continuously receive serial data

### ISSUE THREAD

**Issue by pioneerAlone** [MaJerle/gps-nmea-parser#14]
hi!
When reading GPS data through serial port, when using this library, it is found that the data fault tolerance is not very good, and it is easy to cause the process to crash

**Comment by MaJerle** [comment]
This is not providing enough information.

**Comment by pioneerAlone** [comment]
$GPRMC,013206.000,A,3149.8701,N,11708.4971,E,0.00,0.00,200520,,,A*68
$GPRMC,013207.000,A,3149.8701,N,11708.4971,E,0.00,0.00,200520,,,A*69
$GPRMC,013208.000,A,3149.8701,N,11708.4971,E,0.00,0.00,200520,,,A*66
$GPRMC,013209.000,A,3149.8701,N,11708.4971,E,0.00,0.00,200520,,,A*67
$GPRMC,013210.000,A,3149.8701,N,11708.4971,E,0.00,0.00,200520,,,A*6F
$GPRMC,013211.000,A,3149.8701,N,11708.4970,E,0.00,0.00,200520,,,A*6F
$GPRMC,013212.000,A,3149.8701,N,11708.4970,E,0.00,0.00,200520,,,A*6C
The above is serial data, sent out every second.
while(1)
	{

        ret = rcv_gps_tout(fd,&rx,1,2000);
        if(ret == ERR_TOUT){
            printf("[UART] select time out...\n\n");
        }else if(ret == ERR_SERIALR){
            printf("[UART] select error...\n\n");
        }else{
            fprintf(stderr, "%c\n",rx);
            #if 1
            gps_process(&hgps, &rx,1);
            printf("utc time:[%d:%d:%d]",hgps.hours,hgps.minutes,hgps.seconds);
            printf("Latitude: %f degrees\r\n", hgps.latitude);
            printf("Longitude: %f degrees\r\n", hgps.longitude);
            printf("Altitude: %f meters\r\n", hgps.altitude);
            #endif
        }
	}
This is the parsed code，However, after the program starts, gps_process () is only called once


utc time:[1:43:39]Latitude: 0.000000 degrees
Longitude: 0.000000 degrees
Altitude: 0.000000 meters

root@am335x:/home/amcode# 
The above content indicates that the program performs a parsing and the process hangs.

**Comment by pioneerAlone** [comment]
Found the problem, using static gps_t, caused,
